#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "r3"
name = "REI3"
description.en = "Build and host powerful applications with full control and ownership"
description.fr = "Créez et hébergez des applications puissantes avec un contrôle et une propriété totale"

version = "3.10.4~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://rei3.de/"
demo = "https://demo.rei3.de/#/home"
admindoc = "https://rei3.de/en/docs/admin"
code = "https://github.com/r3-team/r3"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://rei3.de/downloads/REI3_3.10.4_x64_linux.tar.gz"
    amd64.sha256 = "db44e4b731e9b49b656756352b7b00c06dc8aea404e67576132c62b390244ccc"
    arm64.url = "https://rei3.de/downloads/REI3_3.10.4_arm64_linux.tar.gz"
    arm64.sha256 = "ae67c54426db47216c6098b2c6702555107347cb387fe7f105cd9d46164b4a97"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "certificates", "files", "transfer", "database", "temp" ]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-client, imagemagick, ghostscript"

    [resources.database]
    type = "postgresql"
